version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '3001:3001'
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=shivansi789
      - MYSQL_DB=project
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - '3000:80'
    depends_on:
      - server

  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=shivansi789
      - MYSQL_DATABASE=project
      - MYSQL_USER=root
      - MYSQL_PASSWORD=shivansi789
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
